# Generated by Django 5.1.2 on 2024-11-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Satellite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("purpose", models.CharField(max_length=200)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (" Активен", "Активен"),
                            ("Неактивен", "Неактивен"),
                            ("Сгорел", "Сгорел"),
                        ],
                        max_length=200,
                    ),
                ),
                ("is_frequency_violator", models.BooleanField()),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("launch_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tle_0", models.CharField(max_length=200)),
                ("tle_1", models.CharField(max_length=200)),
                ("tle_2", models.CharField(max_length=200)),
                ("update_date", models.DateField()),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.satellite",
                    ),
                ),
            ],
            options={
                "verbose_name": "TLE",
                "verbose_name_plural": "TLEs",
                "ordering": ["-update_date"],
            },
        ),
        migrations.CreateModel(
            name="Transmitter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Передатчик", "Передатчик"),
                            ("Приёмник", "Приёмник"),
                            ("Приёмопередатчик", "Приёмопередатчик"),
                        ],
                        max_length=200,
                    ),
                ),
                ("status", models.CharField(max_length=200)),
                ("modulation", models.CharField(max_length=200)),
                ("upper_frequency_up", models.FloatField(blank=True, null=True)),
                ("lower_frequency_up", models.FloatField(blank=True, null=True)),
                ("upper_frequency_down", models.FloatField(blank=True, null=True)),
                ("lower_frequency_down", models.FloatField(blank=True, null=True)),
                ("baud_rate", models.FloatField()),
                ("is_inverted", models.BooleanField(default=False)),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.satellite",
                    ),
                ),
            ],
        ),
    ]
