# Generated by Django 4.2.16 on 2024-11-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satellite",
            name="identifier",
            field=models.CharField(
                error_messages={"unique": "Такой идентификатор уже существует"},
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="name",
            field=models.CharField(
                error_messages={"unique": "Такое название уже существует"},
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transmitter",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transmitters",
                to="web_app.satellite",
            ),
        ),
        migrations.AlterField(
            model_name="transmitter",
            name="status",
            field=models.CharField(
                choices=[("Активен", "Активен"), ("Неактивен", "Неактивен")],
                max_length=200,
            ),
        ),
    ]
