# Generated by Django 4.2.16 on 2024-11-04 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0002_alter_satellite_identifier_alter_satellite_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="satellite",
            old_name="image_url",
            new_name="image",
        ),
    ]
